/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.scify.jthinkfreedom.talkandplay.gui.users;

import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.scify.jthinkfreedom.talkandplay.gui.MainFrame;
import org.scify.jthinkfreedom.talkandplay.gui.MainPanel;
import org.scify.jthinkfreedom.talkandplay.gui.helpers.GuiHelper;
import org.scify.jthinkfreedom.talkandplay.models.User;
import org.scify.jthinkfreedom.talkandplay.services.UserService;

public class CreateUserPanel extends javax.swing.JPanel {

    private String userImage;
    private MainFrame parent;
    private UserService userService;
    private GuiHelper guiHelper;

    public CreateUserPanel(MainFrame parent) {
        this.guiHelper = new GuiHelper();
        this.parent = parent;
        this.userService = new UserService();
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        createUserPanel = new javax.swing.JPanel();
        nameTextField = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        rotationSpeedSlider = new javax.swing.JSlider();
        rotationSpeedLabel = new javax.swing.JLabel();
        backgroundColorLabel = new javax.swing.JLabel();
        whiteRadioButton = new javax.swing.JRadioButton();
        blackRadioButton = new javax.swing.JRadioButton();
        createUserButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        jButton1.setText("jButton1");

        createUserPanel.setBackground(new java.awt.Color(255, 255, 255));

        nameTextField.setBackground(new java.awt.Color(255, 255, 255));
        nameTextField.setForeground(new java.awt.Color(51, 51, 51));
        nameTextField.setText("Γράψε όνομα χρήστη εδώ");
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/jthinkfreedom/talkandplay/resources/no-photo.png"))); // NOI18N
        imageLabel.setText("Ανέβασε φωτογραφία χρήστη");
        imageLabel.setToolTipText("");
        imageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imageLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMouseClicked(evt);
            }
        });

        rotationSpeedSlider.setBackground(new java.awt.Color(255, 255, 255));
        rotationSpeedSlider.setFont(rotationSpeedSlider.getFont());
        rotationSpeedSlider.setForeground(new java.awt.Color(51, 51, 51));
        rotationSpeedSlider.setMajorTickSpacing(1);
        rotationSpeedSlider.setMaximum(10);
        rotationSpeedSlider.setMinimum(1);
        rotationSpeedSlider.setMinorTickSpacing(1);
        rotationSpeedSlider.setPaintLabels(true);
        rotationSpeedSlider.setSnapToTicks(true);
        rotationSpeedSlider.setValue(1);

        rotationSpeedLabel.setText("Επίλεξε ταχύτητα εναλλαγής");

        backgroundColorLabel.setText("Επίλεξε χρώμα φόντου");

        whiteRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        whiteRadioButton.setText("Λευκό");

        blackRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        blackRadioButton.setText("Μαύρο");

        createUserButton.setBackground(new java.awt.Color(75, 161, 69));
        createUserButton.setFont(createUserButton.getFont());
        createUserButton.setForeground(new java.awt.Color(255, 255, 255));
        createUserButton.setText("Πρόσθεσε νέο χρήστη");
        createUserButton.setBorder(null);
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });

        errorLabel.setFont(errorLabel.getFont());
        errorLabel.setForeground(new java.awt.Color(153, 0, 0));
        errorLabel.setText("error");

        javax.swing.GroupLayout createUserPanelLayout = new javax.swing.GroupLayout(createUserPanel);
        createUserPanel.setLayout(createUserPanelLayout);
        createUserPanelLayout.setHorizontalGroup(
            createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUserPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createUserPanelLayout.createSequentialGroup()
                        .addComponent(createUserButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createUserPanelLayout.createSequentialGroup()
                        .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rotationSpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rotationSpeedLabel))
                                .addGroup(createUserPanelLayout.createSequentialGroup()
                                    .addComponent(whiteRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(blackRadioButton)))
                            .addComponent(backgroundColorLabel))
                        .addGap(137, 137, 137))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createUserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addContainerGap())
        );
        createUserPanelLayout.setVerticalGroup(
            createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUserPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createUserPanelLayout.createSequentialGroup()
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addGroup(createUserPanelLayout.createSequentialGroup()
                        .addComponent(rotationSpeedLabel)
                        .addGap(8, 8, 8)
                        .addComponent(rotationSpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(backgroundColorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(whiteRadioButton)
                            .addComponent(blackRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(createUserButton)))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        String name = nameTextField.getText();

        List<User> users = userService.getUsers();
        for (User user : users) {
            if (user.getName().equals(name)) {
                errorLabel.setText("Το όνομα χρήστη υπάρχει ήδη");
                errorLabel.setVisible(true);
                return;
            }
        }

        if (!name.isEmpty()) {

            User createdUser = new User(name, userImage);
            createdUser.getConfiguration().setRotationSpeed(rotationSpeedSlider.getValue());
            try {
                // Save to xml file
                userService.save(createdUser);
                parent.changePanel(new MainPanel(parent));
            } catch (Exception ex) {
                Logger.getLogger(CreateUserPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void imageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseClicked
        userImage = "";
        JFileChooser chooser = new JFileChooser();

        chooser.setDialogTitle("Διαλέξτε εικόνα");
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.setFileFilter(new FileNameExtensionFilter("Image Files", "png", "jpg", "jpeg", "JPG", "JPEG", "gif"));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            userImage = chooser.getSelectedFile().getAbsolutePath();
            imageLabel.setIcon(guiHelper.getIcon(userImage));
        }
    }//GEN-LAST:event_imageLabelMouseClicked

    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
        if ("Γράψε όνομα χρήστη εδώ".equals(nameTextField.getText())) {
            nameTextField.setText("");
        }
    }//GEN-LAST:event_nameTextFieldFocusGained

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
        if (nameTextField.getText().isEmpty()) {
            nameTextField.setText("Γράψε όνομα χρήστη εδώ");
        }
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void initCustomComponents() {
        errorLabel.setVisible(false);
        nameTextField.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GRAY));
        nameTextField.setFont(new Font("DejaVu Sans", Font.BOLD, 14));
        nameTextField.setHorizontalAlignment(JTextField.CENTER);
        imageLabel.setFont(new Font("DejaVu Sans", Font.BOLD, 14));
        rotationSpeedLabel.setFont(new Font("DejaVu Sans", Font.BOLD, 14));
        backgroundColorLabel.setFont(new Font("DejaVu Sans", Font.BOLD, 14));
        whiteRadioButton.setFont(new Font("DejaVu Sans", Font.PLAIN, 14));
        blackRadioButton.setFont(new Font("DejaVu Sans", Font.PLAIN, 14));
        createUserButton.setFont(new Font("DejaVu Sans", Font.PLAIN, 18));
        createUserButton.setBorder(new LineBorder(new Color(75, 161, 69), 20));
        createUserButton.setMargin(new Insets(10, 10, 10, 10));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundColorLabel;
    private javax.swing.JRadioButton blackRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton createUserButton;
    private javax.swing.JPanel createUserPanel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel rotationSpeedLabel;
    private javax.swing.JSlider rotationSpeedSlider;
    private javax.swing.JRadioButton whiteRadioButton;
    // End of variables declaration//GEN-END:variables
}
