package org.scify.talkandplay.gui.grid.entertainment;

import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.scify.talkandplay.gui.grid.BaseMediaPanel;
import org.scify.talkandplay.gui.grid.GridFrame;
import org.scify.talkandplay.gui.grid.timers.TimerManager;
import org.scify.talkandplay.models.User;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.player.MediaPlayerEventAdapter;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

public class VideoPanel extends BaseMediaPanel {

    private EmbeddedMediaPlayerComponent mediaPlayerComponent;

    private JPanel playerPanel, prevPanel, playPanel, nextPanel, listPanel, exitPanel;

    public VideoPanel(User user, GridFrame parent) {
        super(user, parent, (new File(user.getEntertainmentModule().getVideoModule().getFolderPath())).listFiles());
        mediaPlayerComponent = new EmbeddedMediaPlayerComponent();

        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomComponents() {

        initLayout();

        if (isEmpty()) {
            drawEmpty();
        } else {
            filesPanel = new FilesPanel(user, files, this);

            add(filesPanel, c);
            mediaPlayerPanel.getAudioPlayer().getMediaPlayer().addMediaPlayerEventListener(new MediaPlayerEventAdapter() {
                @Override
                public void finished(MediaPlayer mediaPlayer) {
                    setPlayButton();
                }

                @Override
                public void playing(MediaPlayer mediaPlayer) {
                    setPauseButton();
                }

                @Override
                public void paused(MediaPlayer mediaPlayer) {
                    setPlayButton();
                }
            });
        }

        revalidate();
        repaint();
        parent.clearGrid();
        parent.addGrid(this);
        parent.revalidate();
        parent.repaint();
    }

    public void playFile(String fileName) {
        timer.cancel();
        VideoFrame videoFrame = new VideoFrame(user, getFilePath(fileName), this, filesPanel);
        videoFrame.playMedia(getFilePath(fileName));
    }

    public TimerManager getTimer() {
        return timer;
    }

    public List<JPanel> getControlsList() {
        return controlsList;
    }

    public String getFilePath(String fileName) {
        return user.getEntertainmentModule().getVideoModule().getFolderPath() + fileName;
    }

    private void setPlayButton() {
        ((JLabel) playPanel.getComponent(0)).setText("Αναπαραγωγή");
        ((JLabel) playPanel.getComponent(1)).setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/org/scify/talkandplay/resources/play-button.png")).getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));

    }

    private void setPauseButton() {
        ((JLabel) playPanel.getComponent(0)).setText("Παύση");
        ((JLabel) playPanel.getComponent(1)).setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/org/scify/talkandplay/resources/pause-button.png")).getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));

    }

    public EmbeddedMediaPlayerComponent getMediaPlayerComponent() {
        return this.mediaPlayerComponent;
    }

    public EmbeddedMediaPlayer getMediaPlayer() {
        return this.mediaPlayerComponent.getMediaPlayer();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
