package org.scify.talkandplay.gui.configuration;

import java.awt.Font;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.border.EmptyBorder;
import org.scify.talkandplay.gui.helpers.UIConstants;
import org.scify.talkandplay.models.Category;
import org.scify.talkandplay.models.User;
import org.scify.talkandplay.services.UserService;

public class CommunicationPanel extends javax.swing.JPanel {

    private User user;
    private JLabel label;
    private UserService userService;

    private static final int MARGIN = 20;

    public CommunicationPanel(User user) {
        this.user = user;
        this.userService = new UserService();

        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents() {
        int margin = 0;
        setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        setBorder(new EmptyBorder(20, 20, 20, 20));

        label = new JLabel(user.getCommunicationModule().getName());
        label.setFont(new Font(UIConstants.getMainFont(), Font.BOLD, 16));

        add(label);

        drawCategories(user.getCommunicationModule().getCategories(), MARGIN);

    }

    /**
     * Recursively draw the categories
     *
     * @param categories
     * @param margin
     */
    private void drawCategories(List<Category> categories, int margin) {
        if (categories == null || categories.isEmpty()) {
            return;
        } else {
            margin += MARGIN;
            for (Category category : categories) {
                label = new JLabel(category.getName());
                label.setBorder(new EmptyBorder(8, margin, 0, 0));

                if (category.getSubCategories().size() > 0) {
                    label.setFont(new Font(UIConstants.getMainFont(), Font.BOLD, 14));
                } else {
                    label.setFont(new Font(UIConstants.getMainFont(), Font.PLAIN, 14));
                }

                add(label);
                drawCategories(category.getSubCategories(), margin);
            }
            margin -= MARGIN;
        }
    }

    public void redrawCategoriesList() {
        removeAll();

        System.out.println("sdfdfdsfs");
        label = new JLabel(user.getCommunicationModule().getName());
        label.setFont(new Font(UIConstants.getMainFont(), Font.BOLD, 16));

        add(label);
        user = userService.getUser(user.getName());
        drawCategories(user.getCommunicationModule().getCategories(), MARGIN);

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
