package org.scify.talkandplay.gui.configuration;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.scify.talkandplay.gui.MainFrame;
import org.scify.talkandplay.models.User;
import org.scify.talkandplay.services.CategoryService;
import org.scify.talkandplay.services.UserService;

public class ConfigurationPanel extends javax.swing.JPanel {

    private MainFrame parent;
    private User user;
    private InfoPanel infoPanel;
    private TabsPanel tabsPanel;
    private GridBagConstraints gbc;
    private CategoryService categoryService;

    /**
     * Creates new form ConfigurationPanel
     */
    public ConfigurationPanel(User user, MainFrame parent) {
        this.user = user;
        this.parent = parent;
        this.categoryService = new CategoryService();
        
        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents() {
        parent.setPanelTitle("Προτιμήσεις χρήστη");
        gbc = new GridBagConstraints();
        setLayout(new GridBagLayout());
        gbc.fill = GridBagConstraints.HORIZONTAL;

        gbc.gridx = 0;
        gbc.gridy = 0;
        add(new JLabel(), gbc);
        gbc.gridx = 1;
        gbc.gridy = 0;
        add(new JLabel(), gbc);
        gbc.gridx = 2;
        gbc.gridy = 0;
        add(new JLabel(), gbc);

        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 1;

        gbc.weightx = 1;
      /*  infoPanel = new InfoPanel(this,  user);
        add(infoPanel, gbc);
*/
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1;
        gbc.gridwidth = 2;   
        tabsPanel = new TabsPanel(user, this);
        add(tabsPanel, gbc);

        revalidate();
        repaint();
    }

    public void addPanel(JPanel panel) {
        remove(infoPanel);
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1;
        gbc.gridwidth = 1;
        add(panel, gbc);
        revalidate();
        repaint();
    }
    
    public void redrawCategoriesList(){
        tabsPanel.redrawCategoriesList();
    }
    
    public MainFrame getParent(){
        return this.parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
