package org.scify.talkandplay.gui.configuration;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.apache.commons.lang3.StringUtils;
import org.scify.talkandplay.gui.helpers.GuiHelper;
import org.scify.talkandplay.models.User;
import org.scify.talkandplay.services.ModuleService;

public class EntertainmentPanel extends javax.swing.JPanel {

    private User user;
    private GuiHelper guiHelper;
    private ModuleService moduleService;

    public EntertainmentPanel(User user) {
        this.user = user;
        this.guiHelper = new GuiHelper();
        this.moduleService = new ModuleService();

        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents() {

        guiHelper.setCustomTextField(musicPathTextField);
        guiHelper.setCustomTextField(songSumTextField);
        guiHelper.setCustomTextField(videoPathTextField);

        guiHelper.setStepLabelFont(step1Label);
        guiHelper.setStepLabelFont(step2Label);
        guiHelper.setStepLabelFont(step3Label);

        guiHelper.drawButton(saveButton);
        errorLabel.setVisible(false);

        setListeners();
    }

    private void setListeners() {

        musicPathTextField.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                JFileChooser chooser = new JFileChooser();

                chooser.setDialogTitle("Διάλεξε φάκελο");
                chooser.setAcceptAllFileFilterUsed(false);
                chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                    System.out.println(chooser.getSelectedFile().getAbsolutePath());
                    musicPathTextField.setText(chooser.getSelectedFile().getAbsolutePath());
                }
            }
        });

        videoPathTextField.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                JFileChooser chooser = new JFileChooser();

                chooser.setDialogTitle("Διάλεξε φάκελο");
                chooser.setAcceptAllFileFilterUsed(false);
                chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                    System.out.println(chooser.getSelectedFile().getAbsolutePath());
                    videoPathTextField.setText(chooser.getSelectedFile().getAbsolutePath());
                }
            }
        });

        musicPathTextField.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent fe) {
                if ("Φάκελος μουσικής".equals(musicPathTextField.getText())) {
                    musicPathTextField.setText("");
                }
            }

            public void focusLost(FocusEvent fe) {
                if (musicPathTextField.getText().isEmpty()) {
                    musicPathTextField.setText("Φάκελος μουσικής");
                }
            }
        });

        videoPathTextField.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent fe) {
                if ("Φάκελος video".equals(videoPathTextField.getText())) {
                    videoPathTextField.setText("");
                }
            }

            public void focusLost(FocusEvent fe) {
                if (videoPathTextField.getText().isEmpty()) {
                    videoPathTextField.setText("Φάκελος video");
                }
            }
        });

        songSumTextField.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent fe) {
                if ("Πλήθος".equals(songSumTextField.getText())) {
                    songSumTextField.setText("");
                }
            }

            public void focusLost(FocusEvent fe) {
                if (songSumTextField.getText().isEmpty()) {
                    songSumTextField.setText("Πλήθος");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        step1Label = new javax.swing.JLabel();
        step2Label = new javax.swing.JLabel();
        step3Label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        musicPathTextField = new javax.swing.JTextField();
        videoPathTextField = new javax.swing.JTextField();
        songSumTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        step1Label.setText("1. Επίλεξε φάκελο μουσικής");

        step2Label.setText("2. Επίλεξε φάκελο video");

        step3Label.setText("3. Όρισε πλήθος τραγουδιών και video ανά σελίδα");

        jLabel4.setText("4. Όρισε ένταση ήχου (?)");

        musicPathTextField.setText("Φάκελος μουσικής");

        videoPathTextField.setText("Φάκελος video");

        songSumTextField.setText("10");

        saveButton.setBackground(new java.awt.Color(75, 161, 69));
        saveButton.setFont(saveButton.getFont());
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Αποθήκευση");
        saveButton.setBorder(null);
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(153, 0, 0));
        errorLabel.setText("error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(step2Label))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(step3Label))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(saveButton))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(musicPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(step1Label))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(videoPathTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(songSumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorLabel))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step1Label)
                .addGap(18, 18, 18)
                .addComponent(musicPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(step2Label)
                .addGap(18, 18, 18)
                .addComponent(videoPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(step3Label)
                .addGap(18, 18, 18)
                .addComponent(songSumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addGap(11, 11, 11)
                .addComponent(saveButton)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked

        if (musicPathTextField.getText().isEmpty() || "Φάκελος μουσικής".equals(musicPathTextField.getText())) {
            errorLabel.setText("Ο φάκελος μουσικής πρέπει να οριστεί.");
            errorLabel.setVisible(true);
        } else if (videoPathTextField.getText().isEmpty() || "Φάκελος video".equals(videoPathTextField.getText())) {
            errorLabel.setText("Ο φάκελος video πρέπει να οριστεί.");
            errorLabel.setVisible(true);
        } else if (songSumTextField.getText().isEmpty() || !StringUtils.isNumeric(songSumTextField.getText())) {
            errorLabel.setText("Το πλήθος τραγουδιών πρέπει οριστεί σωστά");
            errorLabel.setVisible(true);
        } else {
            errorLabel.setVisible(false);

            user.getEntertainmentModule().getMusicModule().setFolderPath(musicPathTextField.getText());
            user.getEntertainmentModule().getMusicModule().setPlaylistSize(Integer.parseInt(songSumTextField.getText()));
            user.getEntertainmentModule().getVideoModule().setFolderPath(videoPathTextField.getText());

            try {
                moduleService.update(user);
            } catch (Exception ex) {
                Logger.getLogger(EntertainmentPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField musicPathTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField songSumTextField;
    private javax.swing.JLabel step1Label;
    private javax.swing.JLabel step2Label;
    private javax.swing.JLabel step3Label;
    private javax.swing.JTextField videoPathTextField;
    // End of variables declaration//GEN-END:variables
}
