/**
* Copyright 2016 SciFY
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
package org.scify.talkandplay.gui.configuration;

import java.awt.Font;
import javax.swing.JTextArea;
import org.scify.talkandplay.gui.helpers.GuiHelper;
import org.scify.talkandplay.gui.helpers.UIConstants;
import org.scify.talkandplay.utils.ResourceManager;

/**
 *
 * @author christina
 */
public class GamesInfoPanel extends javax.swing.JPanel {

    private ConfigurationPanel parent;
    private GuiHelper guiHelper;
    protected ResourceManager rm;
    
    
    public GamesInfoPanel(ConfigurationPanel parent) {
        this.parent=parent;
        this.guiHelper = new GuiHelper();
        this.rm = ResourceManager.getInstance();
        initComponents();
        initCustomComponents();
    }

    public void initCustomComponents() {

        guiHelper.drawButton(backButton);
        
        Font font = new Font(UIConstants.mainFont, Font.BOLD, 16);
        step1Label.setFont(font);
        step2Label.setFont(font);
        step3Label.setFont(font);
        step4Label.setFont(font);
        
        initTextArea(step1TextArea);
        initTextArea(step2TextArea);
        initTextArea(step3TextArea);
        initTextArea(step4TextArea);
        
        jScrollPane1.setBorder(null);
        jScrollPane2.setBorder(null);
        jScrollPane3.setBorder(null);
        jScrollPane4.setBorder(null);
    }

    private void initTextArea(JTextArea textArea) {
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        step1Label = new javax.swing.JLabel();
        step2Label = new javax.swing.JLabel();
        step3Label = new javax.swing.JLabel();
        step4Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        step1TextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        step2TextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        step4TextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        step3TextArea = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(460, 558));
        setMinimumSize(new java.awt.Dimension(460, 558));

        step1Label.setText("1. " + rm.getTextOfXMLTag("selectCategory"));

        step2Label.setText("2. " + rm.getTextOfXMLTag("availability") + "  ");

        step3Label.setText("3. " + rm.getTextOfXMLTag("difficultyLevel") +"  ");

        step4Label.setText("4. " + rm.getTextOfXMLTag("saveButton") + "  ");

        step1TextArea.setColumns(20);
        step1TextArea.setRows(5);
        String selectCategoryText = rm.getTextOfXMLTag("selectCategoryText") +
                "\n\tA. " + rm.getTextOfXMLTag("gameTypeStimulusReaction") +
                "\n\tB. " + rm.getTextOfXMLTag("gameTypeTimeSequence") +
                "\n\tC. " + rm.getTextOfXMLTag("gameTypeFindTheSimilar");
        step1TextArea.setText(selectCategoryText);
        jScrollPane1.setViewportView(step1TextArea);

        step2TextArea.setColumns(20);
        step2TextArea.setRows(5);
        step2TextArea.setText(rm.getTextOfXMLTag("selectAvailabilityText"));
        jScrollPane3.setViewportView(step2TextArea);

        step4TextArea.setColumns(20);
        step4TextArea.setRows(5);
        step4TextArea.setText(rm.getTextOfXMLTag("selectAvailabilitySaveText"));
        jScrollPane4.setViewportView(step4TextArea);

        step3TextArea.setColumns(20);
        step3TextArea.setRows(5);
        step3TextArea.setText(rm.getTextOfXMLTag("selectDifficultyLevelText"));
        jScrollPane2.setViewportView(step3TextArea);

        backButton.setBackground(new java.awt.Color(75, 161, 69));
        backButton.setFont(backButton.getFont());
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText(rm.getTextOfXMLTag("backButton"));
        backButton.setBorder(null);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(step1Label)
                            .addComponent(step2Label)
                            .addComponent(step3Label)
                            .addComponent(step4Label))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step1Label)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        parent.goBack();
    }//GEN-LAST:event_backButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel step1Label;
    private javax.swing.JTextArea step1TextArea;
    private javax.swing.JLabel step2Label;
    private javax.swing.JTextArea step2TextArea;
    private javax.swing.JLabel step3Label;
    private javax.swing.JTextArea step3TextArea;
    private javax.swing.JLabel step4Label;
    private javax.swing.JTextArea step4TextArea;
    // End of variables declaration//GEN-END:variables
}
