/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.scify.talkandplay.gui.configuration;

import java.awt.Font;
import javax.swing.JTextArea;
import org.scify.talkandplay.gui.helpers.GuiHelper;
import org.scify.talkandplay.gui.helpers.UIConstants;

/**
 *
 * @author christina
 */
public class GamesInfoPanel extends javax.swing.JPanel {

    private ConfigurationPanel parent;
    private GuiHelper guiHelper;
    
    
    public GamesInfoPanel(ConfigurationPanel parent) {
        this.parent=parent;
        this.guiHelper = new GuiHelper();
        
        initComponents();
        initCustomComponents();
    }

    public void initCustomComponents() {

        guiHelper.drawButton(backButton);
        
        Font font = new Font(UIConstants.mainFont, Font.BOLD, 16);
        step1Label.setFont(font);
        step2Label.setFont(font);
        step3Label.setFont(font);
        step4Label.setFont(font);
        
        initTextArea(step1TextArea);
        initTextArea(step2TextArea);
        initTextArea(step3TextArea);
        initTextArea(step4TextArea);
        
        jScrollPane1.setBorder(null);
        jScrollPane2.setBorder(null);
        jScrollPane3.setBorder(null);
        jScrollPane4.setBorder(null);
    }

    private void initTextArea(JTextArea textArea) {
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        step1Label = new javax.swing.JLabel();
        step2Label = new javax.swing.JLabel();
        step3Label = new javax.swing.JLabel();
        step4Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        step1TextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        step2TextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        step4TextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        step3TextArea = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(460, 558));
        setMinimumSize(new java.awt.Dimension(460, 558));

        step1Label.setText("1. Επίλεξε κατηγορία");

        step2Label.setText("2. Διαθεσιμότητα  ");

        step3Label.setText("3. Επίπεδο δυσκολίας  ");

        step4Label.setText("4. Αποθήκευση  ");

        step1TextArea.setColumns(20);
        step1TextArea.setRows(5);
        step1TextArea.setText("Επίλεξε κατηγορία για να διαχειριστείς τα παιχνίδια. Οι διαθέσιμες κατηγορίες είναι:\n        A. Ερέθισμα - Αντίδραση\n        B. Χρονική αλληλουχία\n        C. Βρες το όμοιο");
        jScrollPane1.setViewportView(step1TextArea);

        step2TextArea.setColumns(20);
        step2TextArea.setRows(5);
        step2TextArea.setText("Επίλεξε ποιά παιχνίδια θα είναι διαθέσιμα στο χρήστη πατώντας “Διαθέσιμο” ή “Μη Διαθέσιμο”, αντίστοιχα.");
        jScrollPane3.setViewportView(step2TextArea);

        step4TextArea.setColumns(20);
        step4TextArea.setRows(5);
        step4TextArea.setText("Στο κάτω μέρος της λίστας των παιχνιδιών βρες το κουμπί “Αποθήκευση” και πάτησέ το για να αποθηκεύσεις τις επιλογές σου.");
        jScrollPane4.setViewportView(step4TextArea);

        step3TextArea.setColumns(20);
        step3TextArea.setRows(5);
        step3TextArea.setText("Ρύθμισε το επίπεδο δυσκολίας για κάθε παιχνίδι ενεργοποιώντας σε κάθε τετράδα τις εικόνες που επιθυμείς. Για να ενεργοποιήσεις μία εικόνα, κάνε κλικ στο κουτί ακριβώς από κάτω της.");
        jScrollPane2.setViewportView(step3TextArea);

        backButton.setBackground(new java.awt.Color(75, 161, 69));
        backButton.setFont(backButton.getFont());
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Πίσω");
        backButton.setBorder(null);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(step1Label)
                            .addComponent(step2Label)
                            .addComponent(step3Label)
                            .addComponent(step4Label))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step1Label)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        parent.goBack();
    }//GEN-LAST:event_backButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel step1Label;
    private javax.swing.JTextArea step1TextArea;
    private javax.swing.JLabel step2Label;
    private javax.swing.JTextArea step2TextArea;
    private javax.swing.JLabel step3Label;
    private javax.swing.JTextArea step3TextArea;
    private javax.swing.JLabel step4Label;
    private javax.swing.JTextArea step4TextArea;
    // End of variables declaration//GEN-END:variables
}
