/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.scify.talkandplay.gui.configuration;

import java.awt.Color;
import java.awt.Image;
import java.awt.Insets;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;
import org.scify.talkandplay.gui.helpers.UIConstants;
import org.scify.talkandplay.models.games.Game;
import org.scify.talkandplay.models.games.GameImage;

/**
 *
 * @author christina
 */
public class GamePanel extends javax.swing.JPanel {

    private Game game;
    private String img1Path, img2Path, img3Path, img4Path;

    /**
     * Creates new form GamePanel
     */
    public GamePanel(Game game) {
        this.game = game;
        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents() {

        if (game.getImages().size() > 0) {
            setImageIcon(img1Label, game.getImages().get(0).getImage());
        } else {
            setImageIcon(img1Label, null);
        }
        if (game.getImages().size() > 2) {
            setImageIcon(img2Label, game.getImages().get(1).getImage());
        } else {
            setImageIcon(img2Label, null);
        }
        if (game.getImages().size() > 3) {
            setImageIcon(img3Label, game.getImages().get(2).getImage());
        } else {
            setImageIcon(img3Label, null);
        }
        if (game.getImages().size() > 4) {
            setImageIcon(img4Label, game.getImages().get(3).getImage());
        } else {
            setImageIcon(img4Label, null);
        }

        nameLabel.setText(game.getName());
        nameLabel.setVisible(false);
        activeButton.setBackground(Color.white);
        activeButton.setForeground(Color.decode(UIConstants.green));
        activeButton.setBorder(new LineBorder(Color.decode(UIConstants.green), 1));
        activeButton.setMargin(new Insets(10, 10, 10, 10));

        inactiveButton.setBackground(Color.white);
        inactiveButton.setForeground(Color.decode(UIConstants.disabledColor));
        inactiveButton.setBorder(new LineBorder(Color.decode(UIConstants.disabledColor), 1));
        inactiveButton.setMargin(new Insets(3, 3, 3, 3));
    }

    private void setImageIcon(JLabel label, String path) {

        if (path == null || path.isEmpty() || !new File(path).exists()) {
            label.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/org/scify/talkandplay/resources/no-photo.png")).getImage().getScaledInstance(90, 90, Image.SCALE_DEFAULT)));
        } else {
            label.setIcon(new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH)));
        }
    }

    public String getName() {
        return nameLabel.getText();
    }

    public List<GameImage> getImages() {
        List<GameImage> images = new ArrayList();

        GameImage image;
        image = new GameImage(img1Path, checkBox1.isSelected(), 1);
        images.add(image);
        image = new GameImage(img2Path, checkBox1.isSelected(), 2);
        images.add(image);
        image = new GameImage(img3Path, checkBox1.isSelected(), 3);
        images.add(image);
        image = new GameImage(img4Path, checkBox1.isSelected(), 4);
        images.add(image);

        return images;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img1Label = new javax.swing.JLabel();
        checkBox1 = new javax.swing.JCheckBox();
        checkBox2 = new javax.swing.JCheckBox();
        img2Label = new javax.swing.JLabel();
        checkBox3 = new javax.swing.JCheckBox();
        img3Label = new javax.swing.JLabel();
        checkBox4 = new javax.swing.JCheckBox();
        img4Label = new javax.swing.JLabel();
        activeButton = new javax.swing.JButton();
        inactiveButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        img1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/talkandplay/resources/no-photo.png"))); // NOI18N
        img1Label.setMaximumSize(new java.awt.Dimension(90, 90));
        img1Label.setMinimumSize(new java.awt.Dimension(90, 90));
        img1Label.setPreferredSize(new java.awt.Dimension(90, 90));
        img1Label.setVerifyInputWhenFocusTarget(false);

        img2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/talkandplay/resources/no-photo.png"))); // NOI18N
        img2Label.setMaximumSize(new java.awt.Dimension(90, 90));
        img2Label.setMinimumSize(new java.awt.Dimension(90, 90));
        img2Label.setPreferredSize(new java.awt.Dimension(90, 90));
        img2Label.setVerifyInputWhenFocusTarget(false);

        img3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/talkandplay/resources/no-photo.png"))); // NOI18N
        img3Label.setMaximumSize(new java.awt.Dimension(90, 90));
        img3Label.setMinimumSize(new java.awt.Dimension(90, 90));
        img3Label.setPreferredSize(new java.awt.Dimension(90, 90));
        img3Label.setVerifyInputWhenFocusTarget(false);

        img4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/talkandplay/resources/no-photo.png"))); // NOI18N
        img4Label.setMaximumSize(new java.awt.Dimension(90, 90));
        img4Label.setMinimumSize(new java.awt.Dimension(90, 90));
        img4Label.setPreferredSize(new java.awt.Dimension(90, 90));
        img4Label.setVerifyInputWhenFocusTarget(false);

        activeButton.setText("Διαθέσιμο");

        inactiveButton.setText("Μη διαθέσιμο");

        nameLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(img1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(checkBox1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(checkBox2)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(checkBox3)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img4Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(checkBox4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(nameLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(inactiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addComponent(activeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBox3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBox2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBox1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(activeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3)
                                .addComponent(inactiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(img4Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkBox4)
                            .addComponent(nameLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activeButton;
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JCheckBox checkBox2;
    private javax.swing.JCheckBox checkBox3;
    private javax.swing.JCheckBox checkBox4;
    private javax.swing.JLabel img1Label;
    private javax.swing.JLabel img2Label;
    private javax.swing.JLabel img3Label;
    private javax.swing.JLabel img4Label;
    private javax.swing.JButton inactiveButton;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
