package org.scify.talkandplay.gui.configuration;

import java.awt.Color;
import java.awt.Font;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.scify.talkandplay.gui.helpers.UIConstants;
import org.scify.talkandplay.models.User;

public class TabsPanel extends javax.swing.JPanel {

    private User user;
    private CommunicationPanel communicationPanel;

    public TabsPanel(User user) {
        this.user = user;
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsPanel = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));

        tabsPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomComponents() {
        // setLayout(new GridLayout(0, 1, 0, 0));
        communicationPanel = new CommunicationPanel(user);

        tabsPanel.addTab("Επικοινωνία", communicationPanel);
        tabsPanel.addTab("Ψυχαγωγία", null);
        tabsPanel.addTab("Παιχνίδια", null);

        tabsPanel.setSelectedIndex(0);

        tabsPanel.setFont(new Font(UIConstants.getMainFont(), Font.PLAIN, 18));

        tabsPanel.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent ce) {
                tabsPanel.setForeground(Color.decode(UIConstants.getMainColor()));
                tabsPanel.setForegroundAt(tabsPanel.getSelectedIndex(), Color.white);
            }
        });
    }

    public void redrawCategoriesList() {
        communicationPanel.redrawCategoriesList();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabsPanel;
    // End of variables declaration//GEN-END:variables
}
