package org.scify.talkandplay.gui.configuration;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import org.scify.talkandplay.gui.helpers.GuiHelper;
import org.scify.talkandplay.gui.helpers.UIConstants;

public class WordFormPanel extends javax.swing.JPanel {

    private GuiHelper guiHelper;
    private List<String> categories;

    public WordFormPanel(List<String> categories) {
        this.guiHelper = new GuiHelper();
        this.categories = categories;
        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents() {
        //setBorder(new LineBorder(Color.decode(UIConstants.getMainColor()), 1));
        setBorder(BorderFactory.createCompoundBorder(new EmptyBorder(10, 10, 10, 10), new LineBorder(Color.decode(UIConstants.getMainColor()), 1)));
        setUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        step1Label = new javax.swing.JLabel();
        wordTextField = new javax.swing.JTextField();
        step2Label = new javax.swing.JLabel();
        step3Label = new javax.swing.JLabel();
        step3ExplLabel = new javax.swing.JLabel();
        uploadSoundLabel = new javax.swing.JLabel();
        step4Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        step4ExplTextArea = new javax.swing.JTextArea();
        categoriesComboBox = new javax.swing.JComboBox();
        uploadImageLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();

        backButton.setBackground(new java.awt.Color(75, 161, 69));
        backButton.setFont(backButton.getFont());
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Πίσω");
        backButton.setBorder(null);

        setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setText("ΠΡΟΣΘΗΚΗ ΝΕΑΣ ΛΕΞΗΣ");

        step1Label.setText("1. Γράψε λέξη");

        wordTextField.setBackground(new java.awt.Color(255, 255, 255));
        wordTextField.setForeground(new java.awt.Color(51, 51, 51));
        wordTextField.setText("Λέξη");

        step2Label.setText("2. Ανέβασε φωτογραφία");

        step3Label.setText("3. Ανέβασε ηχητικό");

        step3ExplLabel.setText("Εάν δεν ανεβάσεις ηχητικό, θα παίζει προκαθορισμένος ήχος.");

        uploadSoundLabel.setText("uploadSound");

        step4Label.setText("4. Επίλεξε πού ανήκει η λέξη");

        step4ExplTextArea.setBackground(new java.awt.Color(255, 255, 255));
        step4ExplTextArea.setColumns(20);
        step4ExplTextArea.setRows(5);
        step4ExplTextArea.setText("Επίλεξε την λέξη στην οποία υπάγεται η λέξη που προσθέτεις εδώ, ή επίλεξε “ΕΠΙΚΟΙΝΩΝΙΑ” εάν πρόκειται για εντελώς νέα κατηγορία λέξεων.\n");
        step4ExplTextArea.setBorder(null);
        jScrollPane1.setViewportView(step4ExplTextArea);

        categoriesComboBox.setBackground(new java.awt.Color(255, 255, 255));
        categoriesComboBox.setBorder(null);

        uploadImageLabel.setText("uploadImg");

        saveButton.setBackground(new java.awt.Color(75, 161, 69));
        saveButton.setFont(saveButton.getFont());
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Αποθήκευση λέξης");
        saveButton.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(step1Label))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(step2Label))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(step3Label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(step3ExplLabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(step4Label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(uploadImageLabel)
                                    .addComponent(wordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(categoriesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(uploadSoundLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(saveButton)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(step1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(step2Label)
                .addGap(36, 36, 36)
                .addComponent(uploadImageLabel)
                .addGap(2, 2, 2)
                .addComponent(step3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3ExplLabel)
                .addGap(30, 30, 30)
                .addComponent(uploadSoundLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoriesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setUI() {
        titleLabel.setFont(new Font(UIConstants.getMainFont(), Font.BOLD, 16));
        titleLabel.setForeground(Color.decode(UIConstants.getMainColor()));
        titleLabel.setHorizontalAlignment(JLabel.CENTER);

        guiHelper.drawButton(saveButton);
        setStepLabelFont(step1Label);
        setStepLabelFont(step2Label);
        setStepLabelFont(step3Label);
        setStepLabelFont(step4Label);
        setStepExplLabelFont(step3ExplLabel);

        wordTextField.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GRAY));
        wordTextField.setFont(new Font(UIConstants.getMainFont(), Font.ITALIC, 14));
        wordTextField.setHorizontalAlignment(JTextField.CENTER);

        uploadImageLabel.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/org/scify/talkandplay/resources/add-icon.png")).getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH)));
        uploadSoundLabel.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/org/scify/talkandplay/resources/add-icon.png")).getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH)));
        uploadImageLabel.setText("");
        uploadSoundLabel.setText("");
        uploadImageLabel.setHorizontalAlignment(JLabel.CENTER);
        uploadSoundLabel.setHorizontalAlignment(JLabel.CENTER);

        //set up the textarea to look like a text field
        step4ExplTextArea.setEditable(false);
        step4ExplTextArea.setLineWrap(true);
        step4ExplTextArea.setWrapStyleWord(true);
        step4ExplTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jScrollPane1.setBorder(null);

        categoriesComboBox.addItem("[-- Επίλεξε λέξη --]");
        for (String category : categories) {
            categoriesComboBox.addItem(category);
        }

        categoriesComboBox.setBorder(new LineBorder(Color.decode(UIConstants.getMainColor()), 1));
        categoriesComboBox.setFont(new Font(UIConstants.getMainColor(), Font.PLAIN, 14));
        // categoriesComboBox.set
    }

    private void setStepLabelFont(JLabel label) {
        label.setFont(new Font(UIConstants.getMainFont(), Font.BOLD, 14));
    }

    private void setStepExplLabelFont(JLabel label) {
        label.setFont(new Font(UIConstants.getMainFont(), Font.PLAIN, 12));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox categoriesComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel step1Label;
    private javax.swing.JLabel step2Label;
    private javax.swing.JLabel step3ExplLabel;
    private javax.swing.JLabel step3Label;
    private javax.swing.JTextArea step4ExplTextArea;
    private javax.swing.JLabel step4Label;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel uploadImageLabel;
    private javax.swing.JLabel uploadSoundLabel;
    private javax.swing.JTextField wordTextField;
    // End of variables declaration//GEN-END:variables
}
