/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.scify.talkandplay.gui.grid.games;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.scify.talkandplay.gui.helpers.UIConstants;

/**
 *
 * @author christina
 */
public class ButtonPanel extends javax.swing.JPanel {

    private String msg1, msg2;

    public ButtonPanel(String msg1, String msg2) {
        this.msg1 = msg1;
        this.msg2 = msg2;

        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents() {
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        setBackground(Color.white);

        Font font = new Font(UIConstants.mainFont, Font.PLAIN, 30);
        JLabel msg1Label = new JLabel(msg1);
        JLabel msg2Label = new JLabel(msg2);
        msg1Label.setFont(font);
        msg2Label.setFont(font);
        msg1Label.setAlignmentX(Component.CENTER_ALIGNMENT);        
        msg2Label.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel imgLabel = new JLabel();
        imgLabel.setIcon(new ImageIcon(getClass().getResource("/org/scify/talkandplay/resources/button.png")));
        imgLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        add(msg1Label);
        add(Box.createRigidArea(new Dimension(0, 5)));
        add(msg2Label);
        add(Box.createRigidArea(new Dimension(0, 40)));
        add(imgLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
