package org.scify.talkandplay.gui.grid;

import java.awt.GridLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.scify.talkandplay.models.User;
import org.scify.talkandplay.services.UserService;

/**
 * The base panel that holds the grid. All panels that contain a grid inherit
 * from this.
 *
 * @author christina
 */
public class BaseGridPanel extends javax.swing.JPanel {

    protected GridFrame parent;
    protected User user;
    protected UserService userService;
    protected ArrayList<JPanel> panelList;

    protected TimerManager timer;
    protected TileCreator tileCreator;

    protected final int IMAGE_PADDING = 10;

    public BaseGridPanel(User user, GridFrame parent) {
        this.user = user;
        this.parent = parent;
        this.timer = new TimerManager(panelList, user.getConfiguration().getRotationSpeed() * 1000, user.getConfiguration().getRotationSpeed() * 1000);
        this.tileCreator = new TileCreator(user);

        initComponents();
        initListeners();
    }

    private void initListeners() {
        parent.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                timer.cancel();
                tileCreator.freePlayerResources();
                e.getWindow().dispose();
            }
        });
    }

    protected void initLayout(int rows, int columns) {
        GridLayout gridLayout = new GridLayout(rows, columns, IMAGE_PADDING, IMAGE_PADDING);
        setLayout(gridLayout);
    }

    protected void showMainMenu() {
        parent.clearGrid();
        parent.addGrid(new GridPanel(user, parent));
        parent.revalidate();
        parent.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
