package org.scify.talkandplay.gui.grid;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.scify.talkandplay.gui.helpers.GuiHelper;
import org.scify.talkandplay.models.User;
import org.scify.talkandplay.models.sensors.KeyboardSensor;
import org.scify.talkandplay.models.sensors.MouseSensor;
import org.scify.talkandplay.models.sensors.Sensor;
import org.scify.talkandplay.services.SensorService;
import org.scify.talkandplay.services.UserService;
import uk.co.caprica.vlcj.component.AudioMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.player.MediaPlayerEventAdapter;

public class GridFrame extends javax.swing.JFrame {

    private User user;
    private GuiHelper guiHelper;
    private UserService userService;
    private SensorService sensorService;
    private AudioMediaPlayerComponent audioPlayer;
    private Timer timer;
    private int selectedImage;
    private String clickedImage;
    private ArrayList<JPanel> panelList;
    private JPanel communicationPanel;
    private JPanel entertainmentPanel;
    private JPanel gamesPanel;

    protected final int BORDER_SIZE = 5;
    protected final int IMAGE_PADDING = 10;
    private static final int IFW = JComponent.WHEN_IN_FOCUSED_WINDOW;

    public GridFrame(String userName) throws IOException {
        this.userService = new UserService();
        this.user = userService.getUser(userName);
        this.sensorService = new SensorService(user);
        this.audioPlayer = new AudioMediaPlayerComponent();
        this.guiHelper = new GuiHelper();
        this.guiHelper = guiHelper;
        this.panelList = new ArrayList<>();
        initComponents();
        initAudioPlayer();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gridPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        gridPanel.setBackground(new java.awt.Color(255, 255, 255));
        gridPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        gridPanel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout gridPanelLayout = new javax.swing.GroupLayout(gridPanel);
        gridPanel.setLayout(gridPanelLayout);
        gridPanelLayout.setHorizontalGroup(
            gridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gridPanelLayout.setVerticalGroup(
            gridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        getContentPane().add(gridPanel, java.awt.BorderLayout.CENTER);

        logoLabel.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scify/talkandplay/resources/tp_logo_small.png"))); // NOI18N
        logoLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 1));
        getContentPane().add(logoLabel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initAudioPlayer() {

        audioPlayer.getMediaPlayer().addMediaPlayerEventListener(new MediaPlayerEventAdapter() {
            @Override
            public void playing(MediaPlayer mediaPlayer) {
                audioPlayer.getMediaPlayer().mute(false);
                audioPlayer.getMediaPlayer().setVolume(100);
            }

            @Override
            public void finished(MediaPlayer mediaPlayer) {
                if ("communication".equals(clickedImage)) {
                    showCommunication();
                } else if ("entertainment".equals(clickedImage)) {
                    showEntertainment();
                } else if ("games".equals(clickedImage)) {
                    showGames();
                }
            }
        });

        //close the media player when the windows closes
        //also release resources
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                timer.cancel();
                audioPlayer.getMediaPlayer().stop();
                audioPlayer.getMediaPlayer().release();
                e.getWindow().dispose();
            }
        });
    }

    private void initCustomComponents() {
        GridLayout gridLayout = new GridLayout(1, 3, IMAGE_PADDING, IMAGE_PADDING);
        gridPanel.setLayout(gridLayout);
        repaintMenu(gridPanel);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pack();
    }

    public void repaintMenu(JPanel panel) {
        panelList = new ArrayList<>();
        selectedImage = 0;
        gridPanel.removeAll();

        if (user.getCommunicationModule().isEnabled()) {
            communicationPanel = guiHelper.createImagePanel(user.getCommunicationModule().getImage(), user.getCommunicationModule().getName(), this);
            gridPanel.add(communicationPanel);
            panelList.add(communicationPanel);
        }

        if (user.getEntertainmentModule().isEnabled()) {
            entertainmentPanel = guiHelper.createImagePanel(user.getEntertainmentModule().getImage(), user.getEntertainmentModule().getName(), this);
            gridPanel.add(entertainmentPanel);
            panelList.add(entertainmentPanel);
        }

        if (user.getGameModule().isEnabled()) {
            gamesPanel = guiHelper.createImagePanel(user.getGameModule().getImage(), user.getGameModule().getName(), this);
            gamesPanel.setFocusable(true);
            gridPanel.add(gamesPanel);
            panelList.add(gamesPanel);
        }

        setTimer();

        setListeners();
        gridPanel.revalidate();
        gridPanel.repaint();
        remove(panel);
        add(gridPanel);
        revalidate();
        repaint();
    }

    private void setTimer() {
        timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                panelList.get(selectedImage).requestFocusInWindow();
                if (selectedImage == 0) {
                    panelList.get(panelList.size() - 1).setBorder(null);
                    panelList.get(selectedImage).setBorder(BorderFactory.createLineBorder(Color.BLUE, BORDER_SIZE));
                    selectedImage++;
                } else if (selectedImage == panelList.size() - 1) {
                    panelList.get(selectedImage - 1).setBorder(null);
                    panelList.get(selectedImage).setBorder(BorderFactory.createLineBorder(Color.BLUE, BORDER_SIZE));
                    selectedImage = 0;
                } else if (selectedImage < panelList.size() - 1 && selectedImage > 0) {
                    panelList.get(selectedImage - 1).setBorder(null);
                    panelList.get(selectedImage).setBorder(BorderFactory.createLineBorder(Color.BLUE, BORDER_SIZE));
                    selectedImage++;
                }
            }
        }, user.getConfiguration().getRotationSpeed() * 1000, user.getConfiguration().getRotationSpeed() * 1000);
    }

    /**
     * The mouse listeners for each of the three modules
     */
    private void setListeners() {
        final GridFrame gridFrame = this;
        setFocusable(true);

        //launch the communication grid        
        communicationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sensor sensor = new MouseSensor(evt.getButton(), evt.getClickCount(), "mouse");
                if (sensorService.shouldSelect(sensor)) {
                    timer.cancel();
                    clickedImage = "communication";
                    audioPlayer.getMediaPlayer().playMedia(user.getCommunicationModule().getSound());
                }
            }
        });
        communicationPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Sensor sensor = new KeyboardSensor(evt.getKeyCode(), evt.getKeyChar(), "keyboard");
                if (sensorService.shouldSelect(sensor)) {
                    timer.cancel();
                    clickedImage = "communication";
                    audioPlayer.getMediaPlayer().playMedia(user.getCommunicationModule().getSound());
                }
            }
        });

        //launch the entertainment grid        
        entertainmentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sensor sensor = new MouseSensor(evt.getButton(), evt.getClickCount(), "mouse");
                if (sensorService.shouldSelect(sensor)) {
                    timer.cancel();
                    clickedImage = "entertainment";
                    audioPlayer.getMediaPlayer().playMedia(user.getEntertainmentModule().getSound());
                }
            }
        });
        entertainmentPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Sensor sensor = new KeyboardSensor(evt.getKeyCode(), evt.getKeyChar(), "keyboard");
                if (sensorService.shouldSelect(sensor)) {
                    timer.cancel();
                    clickedImage = "entertainment";
                    audioPlayer.getMediaPlayer().playMedia(user.getEntertainmentModule().getSound());
                }
            }
        });

        //launch the games grid        
        gamesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sensor sensor = new MouseSensor(evt.getButton(), evt.getClickCount(), "mouse");
                if (sensorService.shouldSelect(sensor)) {
                    timer.cancel();
                    clickedImage = "games";
                    audioPlayer.getMediaPlayer().playMedia(user.getGameModule().getSound());
                }
            }
        });
        gamesPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Sensor sensor = new KeyboardSensor(evt.getKeyCode(), evt.getKeyChar(), "keyboard");
                if (sensorService.shouldSelect(sensor)) {
                    // timer.cancel();
                    clickedImage = "games";
                    audioPlayer.getMediaPlayer().playMedia(user.getGameModule().getSound());
                }
            }
        });
    }

    private void showCommunication() {
        timer.cancel();
        remove(gridPanel);
        try {
            CommunicationPanel communicationPanel = new CommunicationPanel(user.getName(), this);
        } catch (IOException ex) {
            Logger.getLogger(GridFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void showEntertainment() {
        timer.cancel();
        remove(gridPanel);
        EntertainmentPanel entertainmentPanel = new EntertainmentPanel(user, this);
    }

    private void showGames() {
        timer.cancel();
        remove(gridPanel);
        GamesPanel gamesPanel = new GamesPanel(user, this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gridPanel;
    private javax.swing.JLabel logoLabel;
    // End of variables declaration//GEN-END:variables

}
