package org.scify.talkandplay.gui.grid;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.net.URL;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import org.scify.talkandplay.gui.helpers.UIConstants;

public class TilePanel extends javax.swing.JPanel {

    private String text;
    private String imageString;
    private URL imageUrl;

    public TilePanel(String text, String imageString) {
        this.text = text;
        this.imageString = imageString;
        initComponents();
        initCustomComponents();
    }

    public TilePanel(String text, URL imageUrl) {
        this.text = text;
        this.imageUrl = imageUrl;
        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents() {
        setBackground(Color.white);
        setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        setBorder(new LineBorder(Color.white, 10));

        JLabel textLabel = new JLabel(text);
        textLabel.setFont(new Font(UIConstants.getMainFont(), Font.PLAIN, 35));
        textLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        add(textLabel);

        if (imageString != null && !imageString.isEmpty()) {
            JPanel imagePanel = new ImagePanel(imageString);
            imagePanel.setAlignmentX(Component.CENTER_ALIGNMENT);
            add(imagePanel);
        } else {
            JPanel imagePanel = new ImagePanel(imageUrl);
            imagePanel.setAlignmentX(Component.CENTER_ALIGNMENT);
            add(imagePanel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
